#!/bin/bash

# Test Script for Multi-Token and Threshold Obligation Systems
# This script helps test the functionality by creating specific scenarios

echo "===== MULTI-TOKEN AND OBLIGATION SYSTEM TEST PLAN ====="
echo ""
echo "To test the system, run the game and follow these steps:"
echo ""
echo "TEST 1: Multi-Token Earning"
echo "1. Start a new game"
echo "2. Find Martha (docker) at the docks and use Work command"
echo "   - Should earn coins and possibly Trade tokens"
echo "3. Find a merchant or innkeeper and use Work command"
echo "   - Should earn coins and possibly Common tokens"
echo "4. Build relationship with an NPC to 3+ tokens, then use KeepSecret"
echo "   - Should always earn Trust tokens"
echo "5. Get food item and use ShareLunch during afternoon"
echo "   - Should have 75% chance to earn Common tokens"
echo ""
echo "TEST 2: Negative Obligation Activation (Patron's Debt)"
echo "1. Start with patron at -1 Noble tokens (default)"
echo "2. Check letter queue - patron letters should be at position 3"
echo "3. Perform actions to reach -3 Noble tokens with patron"
echo "4. Check that 'Patron's Heavy Hand' obligation activates"
echo "5. Verify patron letters now go to position 1 and cannot be refused"
echo ""
echo "TEST 3: Positive Obligation Activation (Elena's Trust)"
echo "1. Find Elena (scribe) and build Trust tokens to 5"
echo "2. Check that 'Elena's Devotion' obligation activates"
echo "3. Verify Elena's letters get position 7 and +2 days deadline"
echo ""
echo "TEST 4: Obligation Deactivation"
echo "1. With patron at -3 tokens, earn tokens to reach -2"
echo "2. Verify 'Patron's Heavy Hand' deactivates"
echo "3. Check that letters return to position 3 (Expectation still active)"
echo ""
echo "TEST 5: Trade Bonus Obligation (Martha)"
echo "1. Build Trade tokens with Martha to 4+"
echo "2. Check that 'Martha's Gratitude' activates"
echo "3. Verify trade letters from Martha have +3 coin bonus"
echo ""
echo "EXPECTED NOTIFICATIONS:"
echo "- Token earned: '+1 [Type] token with [NPC]'"
echo "- Obligation activated: '[Obligation Name] is now active'"
echo "- Obligation deactivated: '[Obligation Name] is no longer active'"
echo ""
echo "Press Enter to start the game..."
read

cd /mnt/c/git/wayfarer/src && dotnet run