using Wayfarer.Content;
using Wayfarer.GameState;
using Wayfarer.Services.World;
using Wayfarer.Subsystems.Map;
/// <summary>
/// Orchestrates loading of dependent resources generated by self-contained scenes.
///
/// SINGLE RESPONSIBILITY: Package creation, loading, and integration
/// Called by GameFacade.SpawnSceneWithDynamicContent() and RewardApplicationService.FinalizeSceneSpawns()
///
/// DRY PRINCIPLE: Eliminates duplication of orchestration logic
/// </summary>
public class DependentResourceOrchestrationService
{
    private readonly GameWorld _gameWorld;
    private readonly ContentGenerationFacade _contentGenerationFacade;
    private readonly PackageLoaderFacade _packageLoaderFacade;
    private readonly HexRouteGenerator _hexRouteGenerator;
    private readonly SceneInstantiator _sceneInstantiator;
    private readonly TimeManager _timeManager;

    public DependentResourceOrchestrationService(
        GameWorld gameWorld,
        ContentGenerationFacade contentGenerationFacade,
        PackageLoaderFacade packageLoaderFacade,
        HexRouteGenerator hexRouteGenerator,
        SceneInstantiator sceneInstantiator,
        TimeManager timeManager)
    {
        _gameWorld = gameWorld;
        _contentGenerationFacade = contentGenerationFacade;
        _packageLoaderFacade = packageLoaderFacade;
        _hexRouteGenerator = hexRouteGenerator;
        _sceneInstantiator = sceneInstantiator;
        _timeManager = timeManager;
    }

    /// <summary>
    /// Orchestrate complete dependent resource loading pipeline.
    ///
    /// Pipeline:
    /// 1. Create dynamic package file (JSON on disk)
    /// 2. Load package via PackageLoader (entities → GameWorld collections)
    /// 3. Add specified items to player inventory
    /// 4. Generate routes for world-map locations
    /// 5. Build marker resolution map
    ///
    /// IDEMPOTENCY: Safe to call multiple times (package loader handles duplicates)
    /// </summary>
    /// <param name="scene">Scene that generated the resources</param>
    /// <param name="dependentSpecs">Resource specifications from finalization</param>
    /// <param name="player">Player to receive items</param>
    public void LoadDependentResources(Scene scene, DependentResourceSpecs dependentSpecs, Player player)
    {
        if (!dependentSpecs.HasResources)
        {
            return;
        }

        Console.WriteLine($"[DependentResources] Scene '{scene.Id}' has dependent resources");
        Console.WriteLine($"[DependentResources]   Locations: {dependentSpecs.CreatedLocationIds.Count}, Items: {dependentSpecs.ItemsToAddToInventory.Count}");

        _contentGenerationFacade.CreateDynamicPackageFile(dependentSpecs.PackageJson, dependentSpecs.PackageId);
        Console.WriteLine($"[DependentResources] Created dynamic package file: {dependentSpecs.PackageId}");

        _packageLoaderFacade.LoadDynamicPackage(dependentSpecs.PackageJson, dependentSpecs.PackageId);
        Console.WriteLine($"[DependentResources] Loaded dynamic package via PackageLoader");

        foreach (string itemId in dependentSpecs.ItemsToAddToInventory)
        {
            Item item = _gameWorld.Items.FirstOrDefault(i => i.Id == itemId);
            if (item != null)
            {
                // Set provenance tracking
                item.Provenance = new SceneProvenance
                {
                    SceneId = scene.Id,
                    CreatedDay = _timeManager.CurrentDay,
                    CreatedTimeBlock = _timeManager.CurrentTimeBlock,
                    CreatedSegment = _timeManager.CurrentSegment
                };

                player.Inventory.AddItem(item);
                Console.WriteLine($"[DependentResources] Added item to inventory: {item.Name} ({item.Id})");
            }
        }

        foreach (string locationId in dependentSpecs.CreatedLocationIds)
        {
            Location createdLocation = _gameWorld.GetLocation(locationId);
            if (createdLocation != null)
            {
                // Set provenance tracking
                createdLocation.Provenance = new SceneProvenance
                {
                    SceneId = scene.Id,
                    CreatedDay = _timeManager.CurrentDay,
                    CreatedTimeBlock = _timeManager.CurrentTimeBlock,
                    CreatedSegment = _timeManager.CurrentSegment
                };

                Console.WriteLine($"[DependentResources] Created location: {createdLocation.Name} ({createdLocation.Id})");
                Console.WriteLine($"[DependentResources]   VenueId: {createdLocation.VenueId}, HexPosition: {(createdLocation.HexPosition.HasValue ? createdLocation.HexPosition.Value.ToString() : "NONE (intra-venue)")}");

                if (createdLocation.HexPosition.HasValue)
                {
                    List<RouteOption> generatedRoutes = _hexRouteGenerator.GenerateRoutesForNewLocation(createdLocation);
                    foreach (RouteOption route in generatedRoutes)
                    {
                        _gameWorld.Routes.Add(route);
                    }
                    Console.WriteLine($"[DependentResources]   Generated {generatedRoutes.Count} hex routes");
                }
                else
                {
                    Console.WriteLine($"[DependentResources]   No hex position - intra-venue location (travel via venue navigation)");
                }
            }
        }

        _sceneInstantiator.BuildMarkerResolutionMap(scene);
    }
}
