namespace Wayfarer.Services;

/// <summary>
/// Provides tooltip definitions for all game terms.
/// Centralized source of truth for UI explanations.
/// </summary>
public static class TooltipContentProvider
{
    public static readonly Dictionary<string, string> Definitions = new()
    {
        // Conversation Resources
        ["Initiative"] = "Action currency for playing cards. Generated by Remarks (+1) and Observations (+1). Required to play higher-cost cards.",
        ["Momentum"] = "Progress toward conversation goals. Reach 8 (Basic), 12 (Priority), or 16 (Immediate) to complete delivery.",
        ["Doubt"] = "NPC's uncertainty. Conversation fails at 10 Doubt. Reduced by Observations (-1 Doubt each).",
        ["Cadence"] = "Conversation rhythm. +1 per SPEAK, -1 per LISTEN. Positive Cadence adds Doubt when you LISTEN.",
        ["Understanding"] = "Unlocks deeper conversation cards. Gain Understanding by playing Statement cards.",

        // Card Types
        ["Statement"] = "Cards that go to Spoken pile and add to conversation time cost (1 segment per Statement).",
        ["Echo"] = "Cards that return to deck after played. Can be drawn and played multiple times.",
        ["Thought"] = "Cards that persist for the entire conversation and provide ongoing benefits.",

        // Conversational Moves
        ["Remark"] = "Authority-focused cards that generate Initiative (+1) and Momentum. Direct statements.",
        ["Observation"] = "Perception cards that generate Initiative (+1) and reduce Doubt. Analytical insights.",
        ["Argument"] = "High-cost cards requiring multiple Statements in Spoken. Powerful conclusion moves.",

        // Stats
        ["Insight"] = "Analytical intelligence. Better with observational cards. Unlocks systematic investigation (Lv2).",
        ["Rapport"] = "Emotional intelligence. Better with empathetic cards. Unlocks local inquiry (Lv2).",
        ["Authority"] = "Command presence. Better with directive cards. Unlocks demand access (Lv2).",
        ["Diplomacy"] = "Trade acumen. Better with negotiation cards. Unlocks purchase information (Lv2).",
        ["Cunning"] = "Subtlety and misdirection. Better with indirect cards. Unlocks covert search (Lv2).",

        // Player Resources
        ["Health"] = "Physical wellbeing. Restored by rest and medical care. Death at 0.",
        ["Hunger"] = "Food need. Increases over time. High hunger reduces work efficiency and causes health damage.",
        ["Coins"] = "Currency for purchases, exchanges, and services.",
        ["Stamina"] = "Energy for travel. Restored by rest. Required for long journeys.",
        ["Attention"] = "Daily mental energy for investigations and deep work. Refreshes each time block.",

        // Location Mechanics
        ["Familiarity"] = "Location knowledge (0-3). Investigate to increase. Unlocks observations at specific levels.",
        ["Investigation"] = "Spend 1 Attention + 1 Segment to increase Familiarity. Different approaches use different stats.",

        // Queue & Obligations
        ["Queue Position"] = "Letter delivery priority. Must complete Position 1 before others. Can be reordered with tokens.",
        ["Deadline"] = "Time limit for delivery (in segments). Miss deadline = obligation fails and relationship damage.",
        ["Weight"] = "Physical burden. Letters and items have weight. Exceeding capacity slows travel.",

        // Time System
        ["Time Block"] = "Day divided into 6 blocks: Dawn, Morning, Afternoon, Evening, Night, Late Night. Attention refreshes per block.",
        ["Segment"] = "Smallest time unit. 4 segments per time block. Conversations and work consume segments.",

        // Tokens
        ["Trust"] = "Personal connection token. Earned from Basic goals. Used for personal favors.",
        ["Status"] = "Social standing token. Earned from Immediate goals. Used for exclusive access.",
        ["Shadow"] = "Covert connection token. Earned from secret dealings. Used for underground favors.",

        // Personality Types
        ["MERCANTILE"] = "Business-focused. Highest Initiative card gains +3 Momentum.",
        ["DEVOTED"] = "Emotionally invested. All Momentum losses doubled, +1 Doubt on failure.",
        ["PROUD"] = "Status-conscious. Cards must be played in ascending Initiative order.",
        ["CUNNING"] = "Information-focused. Repeat Initiative costs -2 Momentum.",
        ["STEADFAST"] = "Duty-bound. All Momentum changes capped at ±2.",
    };

    public static string Get(string term)
    {
        return Definitions.TryGetValue(term, out string? description) ? description : "";
    }
}
