/// <summary>
/// Data Transfer Object for deserializing Venue location data from JSON.
/// Maps to the structure in location_spots.json.
/// </summary>
public class LocationDTO
{
public string Id { get; set; }
public string Name { get; set; }
public string Type { get; set; }
public string Description { get; set; }
public string InitialState { get; set; }
public string VenueId { get; set; }

/// <summary>
/// Axial hex coordinate Q (nullable for locations not yet placed on grid)
/// Used for dependent locations generated by scenes
/// Parser converts Q,R to AxialCoordinates and assigns to Location.HexPosition
/// </summary>
public int? Q { get; set; }

/// <summary>
/// Axial hex coordinate R (nullable for locations not yet placed on grid)
/// Used for dependent locations generated by scenes
/// Parser converts Q,R to AxialCoordinates and assigns to Location.HexPosition
/// </summary>
public int? R { get; set; }

public List<string> CurrentTimeBlocks { get; set; } = new List<string>();
public List<string> DomainTags { get; set; } = new List<string>();

// The JSON has a "properties" object with time-based keys
public LocationPropertiesDTO Properties { get; set; } = new LocationPropertiesDTO();

// Additional properties from JSON
public bool CanInvestigate { get; set; }
public bool CanWork { get; set; }
public string WorkType { get; set; }
public int WorkPay { get; set; }

// NOTE: Old SceneDTO system deleted - ObservationScene (Mental) and TravelScene (Physical) are SEPARATE systems
// NEW Scene-Situation architecture uses GameWorld.Scenes with PlacementType/PlacementId filtering

// Gameplay properties moved from LocationDTO
public string LocationType { get; set; }
public bool IsStartingLocation { get; set; }
public string ObligationProfile { get; set; }
public Dictionary<string, List<string>> AvailableProfessionsByTime { get; set; } = new Dictionary<string, List<string>>();
public List<WorkActionDTO> AvailableWork { get; set; } = new List<WorkActionDTO>();
}
