/// <summary>
/// Identifies the source of narrative content generation.
/// Used for applying different visual styling in the UI.
/// </summary>
public enum NarrativeProviderType
{
    /// <summary>
    /// Content generated from JSON templates and fallback logic
    /// </summary>
    JsonFallback,
    
    /// <summary>
    /// Content generated by AI using Ollama LLM
    /// </summary>
    AIGenerated
}