/// <summary>
/// Catalogue of all location-specific actions matched by location properties.
/// LocationActions are only available at locations with matching properties.
/// Parser validates JSON actionType against this enum - throws on unknown types.
///
/// ADD NEW ACTIONS:
/// 1. Add enum value here
/// 2. Create intent class in PlayerIntent.cs
/// 3. Add handler in GameFacade.ProcessIntent()
/// 4. Add JSON entry in locationActions array with property requirements
/// </summary>
public enum LocationActionType
{
/// <summary>
/// Navigate to travel routes screen (cross-venue travel)
/// Available at: Locations with Crossroads property
/// Opens route selection UI for inter-venue travel
/// </summary>
Travel,

/// <summary>
/// Instant movement to adjacent location in same venue (intra-venue)
/// Effect: Immediate navigation to destination hex (no route, no cost, no time)
/// Available at: Locations with adjacent locations in same 7-hex venue cluster
/// Generated by: LocationActionCatalog (procedural, based on hex adjacency)
/// Architecture: Same-venue hexes are adjacent by definition, so movement is instant/free
/// </summary>
IntraVenueMove,

/// <summary>
/// Recover health and stamina at safe locations
/// Effect: +1 segment, +5 hunger, +1 health, +1 stamina
/// Available at: Locations with Rest or Restful properties
/// </summary>
Rest,

/// <summary>
/// Pay for secure room with full recovery
/// Effect: Advance to next morning, full health/stamina/focus recovery, hunger reset to 0
/// Available at: Locations with Lodging property
/// Costs: 20 coins (or configured cost)
/// </summary>
SecureRoom,

/// <summary>
/// Earn coins through work
/// Effect: +1 segment, earn 8 coins (modified by hunger)
/// Available at: Locations with Commercial property
/// </summary>
Work,

/// <summary>
/// Gain location familiarity
/// Effect: +1 segment, +familiarity based on location type
/// Available at: Locations with canInvestigate=true
/// </summary>
Investigate,

/// <summary>
/// View delivery job board and accept jobs
/// Effect: Opens job board modal showing available delivery jobs
/// Available at: Locations with Commercial property
/// Generated by: LocationActionCatalog (procedural)
/// </summary>
ViewJobBoard,

/// <summary>
/// Complete active delivery job
/// Effect: Receive payment, clear active job, advance time segment
/// Available at: Destination location when player has active delivery job
/// Generated by: LocationActionManager (query-time, dynamic)
/// </summary>
CompleteDelivery
}
