/// <summary>
/// Template for Situation - immutable archetype embedded in SceneTemplate
/// Defines one narrative moment with 2-4 choice archetypes
/// NOT a standalone entity - always embedded in SceneTemplate
/// At spawn time, instantiated to Situation with placeholders replaced and embedded in Scene
/// </summary>
public class SituationTemplate
{
    /// <summary>
    /// Unique identifier for this SituationTemplate within its SceneTemplate
    /// Used to track which template spawned which Situation instance
    /// Used by SituationSpawnRules to reference transitions
    /// </summary>
    public string Id { get; init; }

    /// <summary>
    /// Display name for this Situation (button label, UI display)
    /// Generated by SceneArchetypeCatalog based on archetype and service type
    /// Example: "Negotiate Lodging", "Access Room", "Rest", "Depart"
    /// Falls back to Situation.Description if null at runtime
    /// </summary>
    public string Name { get; init; }

    /// <summary>
    /// Semantic type marking narrative weight (Normal vs Crisis)
    /// Crisis situations are typically final situations in a Scene that test player preparation
    /// with higher stat requirements or expensive alternatives
    /// Defaults to Normal if not specified in JSON
    /// </summary>
    public SituationType Type { get; init; } = SituationType.Normal;

    /// <summary>
    /// Which tactical system this situation uses (Social, Mental, Physical)
    /// Copied from SituationArchetype.ChallengeType when template generated
    /// Determines which challenge screen appears if player selects challenge path
    /// </summary>
    public TacticalSystemType SystemType { get; init; } = TacticalSystemType.Social;

    /// <summary>
    /// Narrative template with placeholders
    /// Example: "As you approach {LocationName}, {NPCName} steps forward nervously..."
    /// Placeholders replaced at spawn time:
    /// - {NPCName} → actual NPC name
    /// - {LocationName} → actual location name
    /// - {PlayerName} → player character name
    /// - {VenueName} → venue name if applicable
    /// Enables one template to generate varied narrative based on placement
    /// </summary>
    public string NarrativeTemplate { get; init; }

    /// <summary>
    /// Choice templates for this Situation (2-4 enforced by Sir Brante pattern)
    /// Each ChoiceTemplate defines one action option with requirements, costs, rewards
    /// At spawn time, instantiated to Choice instances with placeholders replaced
    /// EMBEDDED - ChoiceTemplates stored inline, not referenced by ID
    /// </summary>
    public List<ChoiceTemplate> ChoiceTemplates { get; init; } = new List<ChoiceTemplate>();

    /// <summary>
    /// Priority for display ordering when multiple Situations available
    /// Higher priority Situations appear first in UI
    /// Default: 0 (normal priority)
    /// </summary>
    public int Priority { get; init; } = 0;

    // ==================== HIERARCHICAL PLACEMENT (OVERRIDE FILTERS) ====================
    // CSS-style inheritance: SituationTemplate can OVERRIDE SceneTemplate base filters
    // Resolution: effectiveFilter = situationFilter ?? sceneBaseFilter
    // All nullable - null means "inherit from scene base"

    /// <summary>
    /// Location filter override for this specific situation
    /// CSS-STYLE INHERITANCE: null = inherit from parent scene's base filter
    /// Resolution: effectiveFilter = this.LocationFilter ?? SceneTemplate.BaseLocationFilter
    /// Non-null = override scene base for this situation only
    /// Enables multi-location scenes: "Negotiate" at Common Room, "Rest" at Private Room
    /// See also: <see cref="SceneTemplate.BaseLocationFilter"/> for inherited default
    /// </summary>
    public PlacementFilter LocationFilter { get; init; }

    /// <summary>
    /// NPC filter override for this specific situation
    /// CSS-STYLE INHERITANCE: null = inherit from parent scene's base filter
    /// Resolution: effectiveFilter = this.NpcFilter ?? SceneTemplate.BaseNpcFilter
    /// Non-null = override scene base for this situation only
    /// Example: Scene has Innkeeper base, but "Depart" situation has null (no NPC)
    /// See also: <see cref="SceneTemplate.BaseNpcFilter"/> for inherited default
    /// </summary>
    public PlacementFilter NpcFilter { get; init; }

    /// <summary>
    /// Route filter override for this specific situation
    /// CSS-STYLE INHERITANCE: null = inherit from parent scene's base filter
    /// Resolution: effectiveFilter = this.RouteFilter ?? SceneTemplate.BaseRouteFilter
    /// Non-null = override scene base for this situation only
    /// Rarely used - most situations don't involve routes
    /// See also: <see cref="SceneTemplate.RouteFilter"/> for inherited default
    /// </summary>
    public PlacementFilter RouteFilter { get; init; }

    /// <summary>
    /// Optional narrative hints for AI generation
    /// If NarrativeTemplate is null/empty, AI generates narrative using these hints
    /// Provides tone, theme, context, style guidance
    /// </summary>
    public NarrativeHints NarrativeHints { get; init; }

    /// <summary>
    /// Specification for creating a dependent location for this situation
    /// Each situation with a spec gets its own location created at spawn time
    /// Direct object binding: situation.Location = PackageLoader.CreateSingleLocation(spec)
    /// Multiple situations can share same spec INSTANCE for shared locations
    /// </summary>
    public DependentLocationSpec DependentLocationSpec { get; init; }
}
