/// <summary>
/// Strongly typed representation of narrative text for a specific card.
/// Used instead of Dictionary to maintain type safety and clarity.
/// </summary>
public class CardNarrative
{
    /// <summary>
    /// The unique identifier of the card this narrative is for.
    /// </summary>
    public string CardId { get; set; }

    /// <summary>
    /// The narrative text to display for this card.
    /// Generated by AI or provided as fallback.
    /// </summary>
    public string NarrativeText { get; set; }

    /// <summary>
    /// Indicates whether this narrative was AI-generated or from fallback/JSON.
    /// Used for UI styling to show AI indicators.
    /// </summary>
    public NarrativeProviderType ProviderSource { get; set; }
}