using Wayfarer.Content;
using Wayfarer.GameState.Enums;
using Wayfarer.Services;

/// <summary>
/// Static factory for creating and initializing GameWorld instances.
/// Uses the new package-based loading system.
/// This is static to ensure clean initialization during startup without DI dependencies.
/// </summary>
public static class GameWorldInitializer
{
    /// <summary>
    /// Creates a new GameWorld instance using the specified content directory.
    /// This method must be static to avoid circular dependencies during startup.
    /// Object references are resolved during parsing (HIGHLANDER Pattern A).
    /// </summary>
    public static GameWorld CreateGameWorld(string contentDirectory = "Content/Core")
    {
        // Create new GameWorld instance
        GameWorld gameWorld = new GameWorld();

        // Create SceneGenerationFacade for parse-time scene generation
        SceneGenerationFacade sceneGenerationFacade = new SceneGenerationFacade(gameWorld);

        // Load content from the specified directory
        // Parsers resolve object references during parsing
        // AI-generated content will go in Content/Generated
        // Test packages are in Content/Test
        PackageLoader packageLoader = new PackageLoader(gameWorld, sceneGenerationFacade);
        packageLoader.LoadPackagesFromDirectory(contentDirectory);

        // NOTE: Procedural routes are generated by PackageLoader (NOT here - avoid duplication)
        // PackageLoader.GenerateProceduralRoutes() is called after hex grid + locations loaded

        // Spawn initial starter Scenes to populate tutorial content
        SpawnInitialScenes(gameWorld);

        return gameWorld;
    }

    /// <summary>
    /// Spawn all SceneTemplates marked as starter content
    /// Creates Active Scenes (not provisional) to populate initial game world
    /// Called during game initialization after content loading
    /// </summary>
    private static void SpawnInitialScenes(GameWorld gameWorld)
    {
        SpawnConditionsEvaluator spawnConditionsEvaluator = new SpawnConditionsEvaluator(gameWorld);
        SceneNarrativeService narrativeService = new SceneNarrativeService(gameWorld);
        MarkerResolutionService markerResolutionService = new MarkerResolutionService();
        SceneGenerationFacade sceneGenerationFacade = new SceneGenerationFacade(gameWorld);
        PackageLoader packageLoader = new PackageLoader(gameWorld, sceneGenerationFacade);
        HexRouteGenerator hexRouteGenerator = new HexRouteGenerator(gameWorld);

        SceneInstantiator instantiator = new SceneInstantiator(gameWorld, spawnConditionsEvaluator, narrativeService, markerResolutionService);

        SceneInstanceFacade sceneInstanceFacade =
            new SceneInstanceFacade(instantiator, gameWorld);

        // TODO: Starter scene spawning moved to GameFacade (proper orchestration layer)
        // GameWorldInitializer should NOT spawn scenes - it lacks orchestration dependencies
        // (ContentGenerationFacade, PackageLoaderFacade, HexRouteGenerator)
        // Starter scenes will be spawned via GameFacade.SpawnStarterScenes() after initialization completes

        // Find all starter templates (for logging only)
        List<SceneTemplate> starterTemplates = gameWorld.SceneTemplates.Where(t => t.IsStarter).ToList();

        Console.WriteLine($"[Init] Found {starterTemplates.Count} starter templates (spawning deferred to GameFacade)");
        foreach (SceneTemplate t in starterTemplates)
        {
            Console.WriteLine($"  - {t.Id} (PlacementFilter: {t.PlacementFilter?.PlacementType})");
        }
    }

    // Helper methods for starter scene spawning REMOVED
    // Starter scene spawning will be implemented in GameFacade with proper orchestration
}